version: '3.8'
services:
    mongo:
        image: mongo:latest
        container_name: mongodb
        restart: unless-stopped
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: password
        ports:
          - 27017:27017
        volumes:
          - ./database-data:/data/db
    cache:
        image: redis:latest
        container_name: redis
        restart: always
        networks:
          - default
        ports:
          - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
        volumes: 
          - ./cache:/data